[features]
seeds = false
[programs.localnet] 
vesting = "6d7MWPKaMnpFkPwU8trzvojcKF4bHm32WXzJiqhQuFXG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
<<<<<<< Updated upstream
cluster = "http://127.0.0.1:8899"
wallet = "/Users/zazza/.config/solana/id.json"
=======
cluster = "devnet"
wallet = "/home/andja/.config/solana/id.json"
>>>>>>> Stashed changes

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
